[project]
name = "airflow-dags"
version = "0.1.0"
description = "Apache Airflow DAGs for orchestrating analytics and data platform workflows."
readme = "README.md"
dependencies = [
    "apache-airflow==3.0.0"
]